### ISSUE TITLE
Service 'beez-fight' failed to build

### ISSUE THREAD

**Issue by DiskorD42** [BSidesSF/ctf-2017-release#1]
Hey there, this is an error I get when I do a build-compose.

```
Step 1/1 : RUN bundle install
 ---> Running in cc0dcfe211d2
Your bundle only supports platforms [] but your local platforms are ["ruby",
"x86_64-linux"], and there's no compatible match between those two lists.
ERROR: Service 'beez-fight' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 16
```
Nothing runs on localhost:8000 or 9000.
I'm new to docker so maybe that is part of the problem. :)

**Comment by iagox86** [comment]
Oh weird.. it worked fine for testing and deploy, but I'm getting that error now on my work PC. I'll push a fix shortly. :)

**Comment by DiskorD42** [comment]
Thank you 👍

**Comment by DiskorD42** [comment]
The problem persists even though I downloaded the new zip.
Maybe thats a problem with me not understanding docker, do i have to undo anything else?

All i did was 
docker-compose kill

and then in the new extracter folder:
docker-compose build && docker-compose up -d

**Comment by iagox86** [comment]
So, that's more of a question for @eastebry, he's our docker guy.

What I'm doing is "docker build -t beez-fight ./". I've never used docker-compose, so I don't know the best way to do that.

**Comment by eastebry** [comment]
I opened https://github.com/BSidesSF/ctf-2017-release/pull/2, which I believe fixes the issue.

Once that is merged in, you should be able to follow the same steps as before.

**Comment by iagox86** [comment]
Looks good to me! Go ahead and merge, and thanks for doing the research!
